### ISSUE TITLE
sgr init gets stuck

### ISSUE THREAD

**Issue by buremba** [splitgraph/splitgraph#274]
Here is the output of `sgr --verbosity DEBUG init`:

```
Initializing engine PostgresEngine LOCAL (sgr@localhost:5432/splitgraph)...
error: Error connecting to the engine (OperationalError: FATAL:  role "sgr" does not exist
error: ), sleeping 5.00s and retrying (1/12)...
error: Error connecting to the engine (OperationalError: FATAL:  role "sgr" does not exist
error: ), sleeping 5.00s and retrying (2/12)...
error: Error connecting to the engine (OperationalError: FATAL:  role "sgr" does not exist
error: ), sleeping 5.00s and retrying (3/12)...
error: Error connecting to the engine (OperationalError: FATAL:  role "sgr" does not exist
error: ), sleeping 5.00s and retrying (4/12)...
.....
```

I have a local PG running if that helps.

**Comment by mildbyte** [comment]
We mostly don't support running Splitgraph against PostgreSQL directly (see the [FAQ](https://www.splitgraph.com/docs/getting-started/frequently-asked-questions#can-i-add-splitgraph-to-my-existing-postgresql-deployment)).

If you're only interested in trying out `sgr mount` (rather than pushing/pulling data), you can create the role `sgr` in your database or change `SG_ENGINE_USER`/`SG_ENGINE_PWD` in your `.sgconfig` file ([docs](https://www.splitgraph.com/docs/configuration/introduction) to the credentials that you use to connect to it. In that case, you don't need to run `sgr init`.

**Comment by buremba** [comment]
I modified `SG_ENGINE_USER=sgr` to `SG_ENGINE_USER=buremba` in `~/.splitgraph/.sgconfig` but `sgr config` command still shows `SG_ENGINE_USER=sgr`. I don't have any file in the current directory btw.

Also, I didn't really intend to use Splitgraph in my local PG but as a data engineer, I just have a local PG running for my personal project. It might be a better idea for Splitgraph to use another port IMO.

**Comment by mildbyte** [comment]
If you don't intend to use local PG, the easiest thing for you might be starting the Splitgraph engine on a different port, for example:

```
sgr engine add --port 5431
```

This should automatically spin up the engine and set up the configuration file to use a different port.

**Comment by mildbyte** [comment]
I'm going to close this for now, feel free to comment if this didn't help!
