### ISSUE TITLE
how to list all available dataset versions

### ISSUE THREAD

**Issue by jsaponara** [splitgraph/splitgraph#321]
I can successfully get the ":latest" version of this dataset:

select * from "cdc-gov/weekly-counts-of-deaths-by-state-and-select-causes-muzy-jte6:latest"."weekly_counts_of_deaths_by_state_and_select_causes"

but how can I query what other versions are available?  Thanks!

**Comment by mildbyte** [comment]
In this case, the dataset is "live", so you always get the latest version proxied to the upstream data portal (you can tell that because the repo page at https://www.splitgraph.com/cdc-gov/weekly-counts-of-deaths-by-state-and-select-causes-muzy-jte6 
 does not have a version dropdown and says "external" instead). For non-live datasets, you can see the version by clicking the dropdown:

![image](https://user-images.githubusercontent.com/828006/96373267-457a2780-1163-11eb-82e6-66deb35af96a.png)

or, alternatively, running the `sgr log` command from the `sgr` client:

```
 $ sgr log --tree --remote data.splitgraph.com splitgraph/socrata
5b02954325 [20200809, 20200809-180313] 2020-08-09 18:02:46
db37ce461e [20200810, 20200810-180340] 2020-08-10 18:03:11
ae7f7a8436 [20201016-120204] 2020-10-16 12:01:47
2ebbea209a [20201016, 20201016-180227] 2020-10-16 18:02:12
fb8e64bdea [20201017-000207] 2020-10-17 00:01:52
f2ac0122fb [20201017-060215] 2020-10-17 06:02:02
f588b5eec2 [20201017-120159] 2020-10-17 12:01:45
0c5595bde1 [20201017, 20201017-180239] 2020-10-17 18:02:23
6dcbe098c8 [20201018-060243] 2020-10-18 06:02:26
90b1b36627 [20201018-120225, 20201018, latest] 2020-10-18 12:02:08
```

Hope this helps!
