### ISSUE TITLE
Non-ASCII characters break query rewriting on the DDN

### ISSUE THREAD

**Issue by tirumaraiselvan** [splitgraph/splitgraph#482]
I was trying to connect Splitgraph with Hasura and it appears the introspection (that Hasura performs) fails with weird errors (like `schema "atalog" not found`). The cause of this seems to be comments like `-- get table info` performed by Hasura. Full SQL here: https://github.com/hasura/graphql-engine/blob/master/server/src-rsr/pg_table_metadata.sql

After removing the comments, the SQL goes through (although not sure if rest of Hasura functionality will work). Note that running the sql with `psql` succeeds as I suppose psql does not send the comments to server...

**Comment by mildbyte** [comment]
@tirumaraiselvan Thanks for raising the issue and the initial investigation!

I managed to replicate and after some bisection narrowed it down to a non-Ascii character in the comment on line 50 (https://github.com/hasura/graphql-engine/blob/master/server/src-rsr/pg_table_metadata.sql#L50):

```
      -- dropped columns still exist in the system catalog as “zombie” columns, so ignore those
```

(see the quotes around "zombie"). When I run the introspection query without those quotes, it works. So I think it's some weird parsing issue where our parser returns positions in byte space whereas, to rewrite the query so that it hits fake introspection tables, we slice the string in character space. This is what causes the offset error after that quote (pg_catalog gets truncated to atalog).

Should be a straightforward fix from our side (operating on the byte string rather than a Unicode string). I'll keep this issue open to track.

**Comment by tirumaraiselvan** [comment]
Cool! Thanks for nailing it down. Feel free to change the issue title.

From our side, it should be trivial to remove the non-ascii character in the comment as well.

**Comment by mildbyte** [comment]
This is now fixed!

![image](https://user-images.githubusercontent.com/828006/124460621-7f3d9d80-dd87-11eb-8cf8-4003865b4e22.png)
